FROM debian:11

# use debian 11 to get python 3.9

RUN apt-get update
RUN apt-get -y install \
  build-essential \
  git \
  libffi-dev \
  python3 \
  python3.9-dev \
  python3.9-venv \
  python3-cffi \
  python3-cffi-backend \
  python3-pycparser \
  python3-dev \
  vim-tiny

RUN git clone https://github.com/OdyseeTeam/lbry-sdk.git
RUN python3 -mvenv /usr/local/lbry
RUN /usr/local/lbry/bin/pip3 install wheel
RUN cd lbry-sdk && /usr/local/lbry/bin/pip3 install .
RUN /usr/local/lbry/bin/pip3 freeze
